### ISSUE TITLE
No such module 'Dance'

### ISSUE THREAD

**Issue by eapen** [saoudrizwan/Dance#11]
I tried the approach of dragging and dropping Dance.swift into my project and saw the error that `No such module 'Dance'`.

I then tried the Cocoapods approach and see that Dance is installed but still get the same error. 

The sample project included with Dance works but I seem to be unable to use this in another project. I tried cleaning and cleaning the build folder to no avail.  

Any suggestions or can you include a demo video?

```
pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using Dance (1.0.6)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

PS. In the DanceExample, I dont see an `import Dance` but only the `import UIKit`

**Comment by saoudrizwan** [comment]
So the reason you don't see `import Dance` in the example project is because `Dance.swift` is part of the module that the project is in. Only when a module is in another scope than the main app's module do you need to import that external module.

As for your issue:
When you're working with cocoapods, make sure you're using `.xcworkspace` and not your `.xcodeproj`. 
If you're trying to drag and drop `Dance.swift` into your project, make sure you drop it in your project folder and select 'Copy if needed'. So like drop it right below `ViewController.swift`.

**Comment by eapen** [comment]
Thank you for explaining. I copied it earlier as part of the project but was still trying to import it in the class and seeing the error. Without the `import Dance` it works as expected.
